repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: flake8
exclude: 'static/recommend/.*|templates/.*|.github/*'
