repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
exclude: 'static/recommend/.*|templates/.*|.github/*'
